/* El catálogo se descarga desde Supabase; las reglas RLS autorizan cada operación. */
const supabaseClient=window.viaRapidaSupabase;
let packages=[];
const money=v=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(v);
const dateLabel=v=>new Intl.DateTimeFormat("es-AR",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`));
const $=s=>document.querySelector(s);const grid=$("#packageGrid"),provinceFilter=$("#provinceFilter"),destinationSearch=$("#destinationSearch"),dateSearch=$("#dateSearch");let cart=[],activePackage=null,adults=1,children=0,busPhotos=[],adminBusPhotos=[];const BUS_BUCKET="bus-gallery";
function initFilters(){[...new Set(packages.map(p=>p.province))].sort().forEach(v=>provinceFilter.add(new Option(v,v)));[...new Set(packages.map(p=>p.destination))].sort().forEach(v=>destinationSearch.add(new Option(v,v)));[...new Set(packages.flatMap(p=>p.departures))].sort().forEach(v=>dateSearch.add(new Option(dateLabel(v),v)))}
function refreshFilterOptions(){const province=provinceFilter.value,destination=destinationSearch.value,date=dateSearch.value;provinceFilter.replaceChildren(new Option("Todas las provincias",""));destinationSearch.replaceChildren(new Option("Todos los destinos",""));dateSearch.replaceChildren(new Option("Cualquier fecha",""));initFilters();if([...provinceFilter.options].some(o=>o.value===province))provinceFilter.value=province;if([...destinationSearch.options].some(o=>o.value===destination))destinationSearch.value=destination;if([...dateSearch.options].some(o=>o.value===date))dateSearch.value=date}function renderPackages(){const province=provinceFilter.value,destination=destinationSearch.value,date=dateSearch.value;const list=packages.filter(p=>(!province||p.province===province)&&(!destination||p.destination===destination)&&(!date||p.departures.includes(date)));grid.innerHTML=list.map(p=>`<article class="package-card"><div class="card-photo"><img src="${p.image}" alt="Paisaje de ${p.destination}" loading="lazy"><span class="photo-gradient"></span><span class="category-badge">${p.category}</span><span class="scarcity-badge ${p.featured.toLowerCase().includes("oferta")?"sale":""}">${p.featured}</span><span class="photo-place">${p.province.toUpperCase()} · ARGENTINA</span></div><div class="card-body"><span class="card-duration">${p.nights} noches · ${p.days} días</span><h3>${p.destination}</h3><p class="card-description">${p.description}</p><div class="includes-list">${p.includes.map(i=>`<span class="include-chip">${i}</span>`).join("")}</div><div class="card-divider"></div><div class="card-price-row"><div><span class="price-label">Desde · por persona</span><strong class="card-price">${money(p.price)}</strong></div><span class="price-note">ARS</span></div><div class="card-actions"><button class="button button-outline" data-action="detail" data-id="${p.id}">Ver detalle</button><button class="button button-primary" data-action="book" data-id="${p.id}">Reservar ahora</button></div></div></article>`).join("");$("#resultsCount").textContent=`${list.length} ${list.length===1?"experiencia disponible":"experiencias disponibles"}`;$("#emptyState").hidden=list.length!==0;$("#clearFilters").hidden=!(province||destination||date)}
function fromDatabase(row){const {price_ars,image_url,...pkg}=row;return {...pkg,price:Number(price_ars),image:image_url}}
function toDatabase(pkg){return {id:pkg.id,destination:pkg.destination,province:pkg.province,category:pkg.category,description:pkg.description,itinerary:pkg.itinerary,nights:pkg.nights,days:pkg.days,includes:pkg.includes,price_ars:pkg.price,spots:pkg.spots,departures:pkg.departures,image_url:pkg.image,featured:pkg.featured,published:pkg.published}}
function busPhotoUrl(path){return supabaseClient.storage.from(BUS_BUCKET).getPublicUrl(path).data.publicUrl}
function renderBusGallery(){const grid=$("#busGalleryGrid");grid.innerHTML=busPhotos.map(photo=>`<figure class="bus-photo"><img src="${busPhotoUrl(photo.storage_path)}" alt="${safeText(photo.description||"Ómnibus de Grupo Vía Rápida")}" loading="lazy"><figcaption>${safeText(photo.description||"Flota de Grupo Vía Rápida")}</figcaption></figure>`).join("");$("#busGalleryStatus").textContent=busPhotos.length?`${busPhotos.length} ${busPhotos.length===1?"vehículo":"vehículos"} en la galería.`:"Todavía estamos preparando la galería. Consultanos por disponibilidad."}
function renderBusAdmin(){const grid=$("#busAdminGrid");grid.innerHTML=adminBusPhotos.map(photo=>`<figure class="bus-admin-photo"><img src="${busPhotoUrl(photo.storage_path)}" alt="${safeText(photo.description||"Ómnibus")}"><figcaption>${safeText(photo.description||"Sin descripción")}</figcaption><button type="button" data-delete-bus-photo="${photo.id}" aria-label="Eliminar foto">Eliminar foto</button></figure>`).join("")||`<p class="manager-note">Todavía no hay fotos cargadas.</p>`}
async function loadBusPhotos(showAll=false){if(!supabaseClient){$("#busGalleryStatus").textContent="La galería estará disponible próximamente.";return false}let query=supabaseClient.from("bus_photos").select("*");if(!showAll)query=query.eq("published",true);const {data,error}=await query.order("created_at",{ascending:false});if(error){console.error(error);if(showAll)$("#busAdminNotice").textContent="No se pudo acceder a bus_photos. Ejecutá supabase-bus-gallery.sql en Supabase.";else $("#busGalleryStatus").textContent="La galería estará disponible próximamente.";return false}if(showAll){adminBusPhotos=data||[];renderBusAdmin()}else{busPhotos=data||[];renderBusGallery()}return true}
async function loadPackages(showAll=false){if(!supabaseClient){$("#resultsCount").textContent="No se pudo iniciar la conexión a Supabase.";return false}let query=supabaseClient.from("packages").select("*");if(!showAll)query=query.eq("published",true);const {data,error}=await query.order("destination");if(error){console.error(error);$("#resultsCount").textContent="No se pudieron cargar los paquetes desde el servidor.";return false}packages=(data||[]).map(fromDatabase);refreshFilterOptions();renderPackages();if(showAll)drawManagerList();return true}function byId(id){return packages.find(p=>p.id===id)}
function openDetail(id){const p=byId(id);if(!p)return;$("#detailContent").innerHTML=`<img class="detail-image" src="${p.image}" alt="Paisaje de ${p.destination}"><div class="detail-body"><p class="eyebrow">${p.category.toUpperCase()} · ${p.province.toUpperCase()}</p><h2 id="detailTitle">${p.destination} <em>te espera</em></h2><p>${p.description}</p><div class="detail-facts"><span>◷ ${p.nights} noches / ${p.days} días</span><span>♧ ${p.spots} cupos disponibles</span><span>↗ ${p.departures.length} fechas de salida</span></div><p><strong>Un viaje para disfrutar</strong><br>${p.itinerary}</p><div class="detail-includes"><strong>El paquete incluye:</strong><br>${p.includes.map(i=>`✓ ${i}`).join("<br>")}</div><div class="detail-footer"><strong>${money(p.price)} <small style="font:400 10px var(--body)">por persona</small></strong><button class="button button-primary" data-action="book" data-id="${p.id}">Reservar ahora →</button></div></div>`;$("#detailDialog").showModal()}
function openBooking(id){const p=byId(id);if(!p)return;activePackage=p;adults=1;children=0;$("#bookingSummary").innerHTML=`<img src="${p.image}" alt="${p.destination}"><p class="summary-label">TU PRÓXIMO DESTINO</p><h3>${p.destination}</h3><p>${p.nights} noches · ${p.days} días<br>${p.includes.join(" · ")}</p><strong>${money(p.price)} <small style="font:400 9px var(--body)">/ persona</small></strong>`;$("#bookingForm").reset();$("#bookingPackageId").value=p.id;const dep=$("#bookingDeparture");dep.replaceChildren(...p.departures.map(d=>new Option(dateLabel(d),d)));$("#adultCount").textContent=1;$("#childCount").textContent=0;$("[name=adults]").value=1;$("[name=children]").value=0;$("#bookingDialog").showModal()}
function openCart(){$("#cartContent").innerHTML=cart.length?`<div class="cart-list">${cart.map((x,i)=>`<div class="cart-item"><img src="${x.image}" alt=""><div><strong>${x.destination}</strong><small>${dateLabel(x.departure)} · ${x.travelers} viajeros</small></div><button data-remove="${i}">Quitar</button></div>`).join("")}</div>`:`<p class="cart-empty">Todavía no tenés reservas. Encontrá tu próximo viaje y guardalo acá.</p>`;$("#cartDialog").showModal()}
function updateCart(){$("#cartCount").textContent=cart.length}
document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;if(b.dataset.action==="detail")openDetail(b.dataset.id);if(b.dataset.action==="book"){$("#detailDialog").close();openBooking(b.dataset.id)}});
provinceFilter.addEventListener("change",renderPackages);$("#tripSearch").addEventListener("submit",e=>{e.preventDefault();renderPackages();$("#paquetes").scrollIntoView({behavior:"smooth"})});$("#clearFilters").addEventListener("click",()=>{provinceFilter.value="";destinationSearch.value="";dateSearch.value="";renderPackages()});$("#cartButton").addEventListener("click",openCart);$("#cartContent").addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(b){cart.splice(Number(b.dataset.remove),1);updateCart();openCart()}});
document.addEventListener("click",e=>{const b=e.target.closest("[data-step]");if(b){const key=b.dataset.step,delta=Number(b.dataset.change);if(key==="adults")adults=Math.max(1,Math.min(9,adults+delta));else children=Math.max(0,Math.min(9,children+delta));$(key==="adults"?"#adultCount":"#childCount").textContent=key==="adults"?adults:children;$(`[name=${key}]`).value=key==="adults"?adults:children}if(e.target.matches("[data-close]"))e.target.closest("dialog").close()});
$("#bookingForm").addEventListener("submit",e=>{e.preventDefault();if(!activePackage)return;const f=new FormData(e.currentTarget),departure=f.get("departure"),payment=f.get("payment"),installments=f.get("installments"),adultQty=Number(f.get("adults")),childQty=Number(f.get("children")),total=activePackage.price*adultQty,first=f.get("firstName"),last=f.get("lastName"),dni=f.get("dni"),email=f.get("email"),phone=f.get("phone");cart.push({...activePackage,departure,travelers:adultQty+childQty,adults:adultQty,children:childQty,total});updateCart();
  $("#successSummary").innerHTML=`<strong>${activePackage.destination} (${activePackage.id})</strong><br>Salida: ${dateLabel(departure)} · ${activePackage.nights} noches / ${activePackage.days} días<br>Pasajero: ${first} ${last} · DNI ${dni}<br>Correo: ${email} · Celular: ${phone}<br>Viajeros: ${adultQty} adultos (mayores de 4 años) · ${childQty} menores (menores de 4 años)<br>Pago: ${payment} · ${installments} ${Number(installments)===1?"cuota":"cuotas"}<br>Precio por adulto: ${money(activePackage.price)} · Total estimado (adultos; tarifa de menores a confirmar): ${money(total)}`;
  const msg=`Hola, somos grupoviarapida. Gracias por elegirnos. Quiero continuar con esta reserva.\n\nDATOS DEL VIAJE\nPaquete: ${activePackage.destination} (${activePackage.id})\nProvincia: ${activePackage.province}\nSalida: ${dateLabel(departure)}\nDuración: ${activePackage.nights} noches / ${activePackage.days} días\n\nDATOS DEL PASAJERO\nNombre y apellido: ${first} ${last}\nDNI: ${dni}\nCorreo electrónico: ${email}\nCelular: ${phone}\n\nINTEGRANTES\nAdultos (mayores de 4 años): ${adultQty}\nMenores (menores de 4 años): ${childQty}\n\nMODALIDAD DE PAGO\nMedio: ${payment}\nCuotas: ${installments}\nPrecio por adulto: ${money(activePackage.price)}\nTotal estimado (adultos; tarifa de menores a confirmar): ${money(total)}\n\nUn asesor se pondrá en contacto para continuar con el proceso y puedas disfrutar del destino que elegiste.`;
  $("#whatsappLink").href=`https://wa.me/5493624331163?text=${encodeURIComponent(msg)}`;$("#bookingDialog").close();e.currentTarget.reset();$("#successDialog").showModal()});$("#menuToggle").addEventListener("click",()=>{const n=$(".main-nav"),open=n.classList.toggle("is-open");$("#menuToggle").setAttribute("aria-expanded",String(open))});$(".main-nav").addEventListener("click",e=>{if(e.target.closest("a")){$(".main-nav").classList.remove("is-open");$("#menuToggle").setAttribute("aria-expanded","false")}});
initFilters();renderPackages();






/* Gestor visual sencillo para editar el catálogo desde la misma página. */
const adminDialog=$("#packageManagerDialog"),adminForm=$("#packageAdminForm"),loginDialog=$("#adminLoginDialog");
function safeText(value){return String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function drawManagerList(){$("#managerItems").innerHTML=packages.map(p=>`<article class="manager-item"><div><strong>${safeText(p.destination)}</strong><small>${safeText(p.province)} · ${money(p.price)}</small></div><button type="button" data-edit-package="${safeText(p.id)}">Editar</button><button type="button" class="manager-delete" data-delete-package="${safeText(p.id)}">Eliminar</button></article>`).join("")||`<div class="cart-empty">Todavía no hay paquetes.<br><small>Podés crear el primero o cargar los ejemplos iniciales.</small><br><button class="button button-outline" type="button" data-import-examples>Cargar paquetes de ejemplo</button></div>`}
function resetPackageEditor(){adminForm.reset();adminForm.elements.namedItem("id").value="";$("#editorTitle").textContent="Nuevo paquete";$("#managerNotice").textContent=""}
function openPackageEditor(id){resetPackageEditor();if(id){const p=byId(id);if(!p)return;$("#editorTitle").textContent=`Editar ${p.destination}`;for(const key of ["id","destination","province","category","featured","description","itinerary","nights","days","price","spots","image"])adminForm.elements.namedItem(key).value=p[key];adminForm.elements.namedItem("includes").value=p.includes.join(", ");adminForm.elements.namedItem("departures").value=p.departures.join(", ");adminForm.elements.namedItem("published").checked=p.published}adminDialog.showModal()}
async function openManager(){const {data,error}=await supabaseClient.auth.getSession();if(error){$("#loginNotice").textContent="No se pudo validar la sesión.";loginDialog.showModal();return}if(data.session){const loaded=await loadPackages(true);if(loaded){resetPackageEditor();await loadBusPhotos(true);adminDialog.showModal()}else{$("#resultsCount").textContent="No se pudo leer packages; revisá tus políticas RLS."}return}$("#adminLoginForm").reset();$("#loginNotice").textContent="";loginDialog.showModal()}
$("#openPackageManager").addEventListener("click",e=>{e.preventDefault();openManager()});$("#adminLoginForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);$("#loginNotice").textContent="Ingresando…";const {error}=await supabaseClient.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(error){$("#loginNotice").textContent="No se pudo iniciar sesión. Revisá correo y contraseña.";return}loginDialog.close();const loaded=await loadPackages(true);if(loaded){resetPackageEditor();await loadBusPhotos(true);adminDialog.showModal()}else{$("#loginNotice").textContent="Entraste, pero no hay permisos para leer paquetes. Revisá las políticas RLS.";loginDialog.showModal()}});
$("#managerLogout").addEventListener("click",async()=>{await supabaseClient.auth.signOut();adminDialog.close();resetPackageEditor()});$("#newPackage").addEventListener("click",()=>openPackageEditor());$("#cancelEdit").addEventListener("click",resetPackageEditor);
$("#managerItems").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit-package]"),remove=e.target.closest("[data-delete-package]");if(edit)openPackageEditor(edit.dataset.editPackage);if(e.target.closest("[data-import-examples]")){if(!confirm("Se agregarán paquetes ficticios de ejemplo con precios y fechas ilustrativos. Revisalos antes de publicar. ¿Continuar?"))return;const demo=window.viaRapidaInitialPackages.map(p=>toDatabase({...p,published:true}));const {error}=await supabaseClient.from("packages").insert(demo);if(error){$("#managerNotice").textContent="No se pudieron importar los ejemplos; verificá que la tabla esté vacía.";return}await loadPackages(true);return}if(remove){const p=byId(remove.dataset.deletePackage);if(!p||!confirm(`¿Eliminar el paquete ${p.destination}?`))return;const {error}=await supabaseClient.from("packages").delete().eq("id",p.id);if(error){$("#managerNotice").textContent="No se pudo eliminar. Revisá las políticas RLS.";return}await loadPackages(true);$("#managerNotice").textContent=`${p.destination} eliminado.`}});
$("#busAdminGrid").addEventListener("click",async e=>{const button=e.target.closest("[data-delete-bus-photo]");if(!button)return;const photo=adminBusPhotos.find(p=>p.id===button.dataset.deleteBusPhoto);if(!photo||!confirm("¿Eliminar esta foto de la galería?"))return;const {error:storageError}=await supabaseClient.storage.from(BUS_BUCKET).remove([photo.storage_path]);if(storageError){$("#busAdminNotice").textContent="No se pudo eliminar el archivo de Storage.";return}const {error}=await supabaseClient.from("bus_photos").delete().eq("id",photo.id);if(error){$("#busAdminNotice").textContent="Se eliminó el archivo, pero no el registro de la galería.";return}$("#busAdminNotice").textContent="Foto eliminada.";await loadBusPhotos(true);await loadBusPhotos(false)});adminForm.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(adminForm),existingId=f.get("id"),departures=f.get("departures").split(",").map(v=>v.trim()).filter(Boolean),image=f.get("image").trim();if(!departures.length||departures.some(d=>!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(d))){$("#managerNotice").textContent="Ingresá al menos una fecha con formato AAAA-MM-DD.";return}if(!/^(https?:\/\/|assets\/)/i.test(image)){$("#managerNotice").textContent="La imagen debe ser una URL segura o estar dentro de assets/.";return}const item={id:existingId||`ARG-${Date.now().toString().slice(-6)}`,destination:f.get("destination").trim(),province:f.get("province").trim(),category:f.get("category").trim(),description:f.get("description").trim(),itinerary:f.get("itinerary").trim(),nights:Number(f.get("nights")),days:Number(f.get("days")),includes:f.get("includes").split(",").map(v=>v.trim()).filter(Boolean),price:Number(f.get("price")),spots:Number(f.get("spots")),departures,image,featured:f.get("featured").trim(),published:f.get("published")==="on"};const payload=toDatabase(item);const result=existingId?await supabaseClient.from("packages").update(payload).eq("id",existingId):await supabaseClient.from("packages").insert(payload);if(result.error){$("#managerNotice").textContent="No se pudo guardar. Revisá que la tabla, sus columnas y las políticas RLS coincidan.";console.error(result.error);return}await loadPackages(true);resetPackageEditor();$("#managerNotice").textContent=`${item.destination} guardado correctamente.`});
loadPackages();loadBusPhotos();$("#busPhotoForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,files=[...form.elements.photos.files],description=new FormData(form).get("description").trim();if(!files.length)return;if(files.some(file=>!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>6*1024*1024)){$("#busAdminNotice").textContent="Usá imágenes JPG, PNG o WebP de hasta 6 MB cada una.";return}const submit=form.querySelector("button[type=submit]");submit.disabled=true;let completed=0;for(const file of files){const cleanName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${Date.now()}-${Math.random().toString(36).slice(2,8)}-${cleanName}`;$("#busAdminNotice").textContent=`Subiendo imagen ${completed+1} de ${files.length}…`;const {data,error:uploadError}=await supabaseClient.storage.from(BUS_BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(uploadError){$("#busAdminNotice").textContent="Falló la carga de una imagen. Revisá la política de Storage y el tamaño del archivo.";break}const {error:rowError}=await supabaseClient.from("bus_photos").insert({storage_path:data.path,description:description||file.name,published:true});if(rowError){await supabaseClient.storage.from(BUS_BUCKET).remove([data.path]);$("#busAdminNotice").textContent="La imagen se subió, pero no se pudo guardar en bus_photos. Ejecutá el SQL de la galería.";break}completed++}submit.disabled=false;if(completed){form.reset();await loadBusPhotos(true);await loadBusPhotos(false);if(completed===files.length)$("#busAdminNotice").textContent=`Se cargaron ${completed} ${completed===1?"imagen":"imágenes"}.`}});





