/* Actualizá, agregá o quitá paquetes en este array para editar el catálogo. */
const packages = [
 {id:"ARG-001",destination:"Cataratas del Iguazú",province:"Misiones",category:"Aventura",description:"Sentí la fuerza de las cataratas desde pasarelas inmersas en la selva misionera.",itinerary:"Garganta del Diablo · Circuito Superior · Parque Nacional",nights:3,days:4,includes:["Hotel 3★","Desayuno","Excursión"],price:489000,spots:2,departures:["2026-10-18","2026-11-08","2026-12-06"],image:"https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=82",featured:"Últimos 2 cupos"},
 {id:"ARG-002",destination:"Bariloche",province:"Río Negro",category:"Montaña",description:"Bosques, lagos y chocolate en una escapada al corazón de la Patagonia.",itinerary:"Circuito Chico · Cerro Campanario · Centro Cívico",nights:4,days:5,includes:["Hotel 4★","Desayuno","Circuito Chico"],price:625000,spots:8,departures:["2026-10-22","2026-11-12","2026-12-10"],image:"https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=82",featured:"Oferta"},
 {id:"ARG-003",destination:"Mendoza",province:"Mendoza",category:"Relax",description:"Un brindis entre viñedos, la cordillera de fondo y sabores inolvidables.",itinerary:"Bodegas de Luján · Degustación · Alta montaña",nights:3,days:4,includes:["Hotel boutique","Desayuno","Tour de bodegas"],price:539000,spots:6,departures:["2026-10-16","2026-11-13","2026-12-04"],image:"https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=82",featured:"Más elegido"},
 {id:"ARG-004",destination:"Salta y Jujuy",province:"Salta",category:"Cultura",description:"Pueblos de altura, cerros de colores y la calidez del norte argentino.",itinerary:"Quebrada de Humahuaca · Purmamarca · Salinas Grandes",nights:5,days:6,includes:["Hotel 3★","Desayuno","Excursiones"],price:715000,spots:4,departures:["2026-10-24","2026-11-14","2026-12-12"],image:"assets/via-rapida-salar.jpeg",featured:"Cupos limitados"},
 {id:"ARG-005",destination:"Puerto Madryn",province:"Chubut",category:"Naturaleza",description:"Viví la Patagonia atlántica y encontrate con su fauna marina única.",itinerary:"Península Valdés · Avistaje · Ecocentro",nights:4,days:5,includes:["Hotel 3★","Desayuno","Península Valdés"],price:668000,spots:7,departures:["2026-10-20","2026-11-17","2026-12-15"],image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=82",featured:"Naturaleza"},
 {id:"ARG-006",destination:"Ushuaia",province:"Tierra del Fuego",category:"Aventura",description:"El fin del mundo entre montañas, mar y paisajes que parecen de otro planeta.",itinerary:"Parque Nacional · Canal Beagle · Tren del Fin del Mundo",nights:4,days:5,includes:["Hotel 3★","Desayuno","Navegación"],price:829000,spots:3,departures:["2026-11-05","2026-11-26","2026-12-17"],image:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=82",featured:"Últimos 3 cupos"}
];
const money=v=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(v);
const dateLabel=v=>new Intl.DateTimeFormat("es-AR",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`));
const $=s=>document.querySelector(s);const grid=$("#packageGrid"),provinceFilter=$("#provinceFilter"),destinationSearch=$("#destinationSearch"),dateSearch=$("#dateSearch");let cart=[],activePackage=null,adults=1,children=0;
function initFilters(){[...new Set(packages.map(p=>p.province))].sort().forEach(v=>provinceFilter.add(new Option(v,v)));[...new Set(packages.map(p=>p.destination))].sort().forEach(v=>destinationSearch.add(new Option(v,v)));[...new Set(packages.flatMap(p=>p.departures))].sort().forEach(v=>dateSearch.add(new Option(dateLabel(v),v)))}
function renderPackages(){const province=provinceFilter.value,destination=destinationSearch.value,date=dateSearch.value;const list=packages.filter(p=>(!province||p.province===province)&&(!destination||p.destination===destination)&&(!date||p.departures.includes(date)));grid.innerHTML=list.map(p=>`<article class="package-card"><div class="card-photo"><img src="${p.image}" alt="Paisaje de ${p.destination}" loading="lazy"><span class="photo-gradient"></span><span class="category-badge">${p.category}</span><span class="scarcity-badge ${p.featured.toLowerCase().includes("oferta")?"sale":""}">${p.featured}</span><span class="photo-place">${p.province.toUpperCase()} · ARGENTINA</span></div><div class="card-body"><span class="card-duration">${p.nights} noches · ${p.days} días</span><h3>${p.destination}</h3><p class="card-description">${p.description}</p><div class="includes-list">${p.includes.map(i=>`<span class="include-chip">${i}</span>`).join("")}</div><div class="card-divider"></div><div class="card-price-row"><div><span class="price-label">Desde · por persona</span><strong class="card-price">${money(p.price)}</strong></div><span class="price-note">ARS</span></div><div class="card-actions"><button class="button button-outline" data-action="detail" data-id="${p.id}">Ver detalle</button><button class="button button-primary" data-action="book" data-id="${p.id}">Reservar ahora</button></div></div></article>`).join("");$("#resultsCount").textContent=`${list.length} ${list.length===1?"experiencia disponible":"experiencias disponibles"}`;$("#emptyState").hidden=list.length!==0;$("#clearFilters").hidden=!(province||destination||date)}
function byId(id){return packages.find(p=>p.id===id)}
function openDetail(id){const p=byId(id);if(!p)return;$("#detailContent").innerHTML=`<img class="detail-image" src="${p.image}" alt="Paisaje de ${p.destination}"><div class="detail-body"><p class="eyebrow">${p.category.toUpperCase()} · ${p.province.toUpperCase()}</p><h2 id="detailTitle">${p.destination} <em>te espera</em></h2><p>${p.description}</p><div class="detail-facts"><span>◷ ${p.nights} noches / ${p.days} días</span><span>♧ ${p.spots} cupos disponibles</span><span>↗ ${p.departures.length} fechas de salida</span></div><p><strong>Un viaje para disfrutar</strong><br>${p.itinerary}</p><div class="detail-includes"><strong>El paquete incluye:</strong><br>${p.includes.map(i=>`✓ ${i}`).join("<br>")}</div><div class="detail-footer"><strong>${money(p.price)} <small style="font:400 10px var(--body)">por persona</small></strong><button class="button button-primary" data-action="book" data-id="${p.id}">Reservar ahora →</button></div></div>`;$("#detailDialog").showModal()}
function openBooking(id){const p=byId(id);if(!p)return;activePackage=p;adults=1;children=0;$("#bookingSummary").innerHTML=`<img src="${p.image}" alt="${p.destination}"><p class="summary-label">TU PRÓXIMO DESTINO</p><h3>${p.destination}</h3><p>${p.nights} noches · ${p.days} días<br>${p.includes.join(" · ")}</p><strong>${money(p.price)} <small style="font:400 9px var(--body)">/ persona</small></strong>`;$("#bookingForm").reset();$("#bookingPackageId").value=p.id;const dep=$("#bookingDeparture");dep.replaceChildren(...p.departures.map(d=>new Option(dateLabel(d),d)));$("#adultCount").textContent=1;$("#childCount").textContent=0;$("[name=adults]").value=1;$("[name=children]").value=0;$("#bookingDialog").showModal()}
function openCart(){$("#cartContent").innerHTML=cart.length?`<div class="cart-list">${cart.map((x,i)=>`<div class="cart-item"><img src="${x.image}" alt=""><div><strong>${x.destination}</strong><small>${dateLabel(x.departure)} · ${x.travelers} viajeros</small></div><button data-remove="${i}">Quitar</button></div>`).join("")}</div>`:`<p class="cart-empty">Todavía no tenés reservas. Encontrá tu próximo viaje y guardalo acá.</p>`;$("#cartDialog").showModal()}
function updateCart(){$("#cartCount").textContent=cart.length}
grid.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;if(b.dataset.action==="detail")openDetail(b.dataset.id);if(b.dataset.action==="book"){$("#detailDialog").close();openBooking(b.dataset.id)}});
provinceFilter.addEventListener("change",renderPackages);$("#tripSearch").addEventListener("submit",e=>{e.preventDefault();renderPackages();$("#paquetes").scrollIntoView({behavior:"smooth"})});$("#clearFilters").addEventListener("click",()=>{provinceFilter.value="";destinationSearch.value="";dateSearch.value="";renderPackages()});$("#cartButton").addEventListener("click",openCart);$("#cartContent").addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(b){cart.splice(Number(b.dataset.remove),1);updateCart();openCart()}});
document.addEventListener("click",e=>{const b=e.target.closest("[data-step]");if(b){const key=b.dataset.step,delta=Number(b.dataset.change);if(key==="adults")adults=Math.max(1,Math.min(9,adults+delta));else children=Math.max(0,Math.min(9,children+delta));$(key==="adults"?"#adultCount":"#childCount").textContent=key==="adults"?adults:children;$(`[name=${key}]`).value=key==="adults"?adults:children}if(e.target.matches("[data-close]"))e.target.closest("dialog").close()});
$("#bookingForm").addEventListener("submit",e=>{e.preventDefault();if(!activePackage)return;const f=new FormData(e.currentTarget),departure=f.get("departure"),payment=f.get("payment"),installments=f.get("installments"),adultQty=Number(f.get("adults")),childQty=Number(f.get("children")),total=activePackage.price*adultQty;cart.push({...activePackage,departure,travelers:adultQty+childQty,adults:adultQty,children:childQty,total});updateCart();const first=f.get("firstName"),last=f.get("lastName");$("#successSummary").innerHTML=`<strong>${activePackage.destination}</strong><br>Salida: ${dateLabel(departure)} · ${activePackage.nights} noches / ${activePackage.days} días<br>Pasajero: ${first} ${last}<br>Viajeros: ${adultQty} adultos · ${childQty} menores<br>Pago: ${payment} · ${installments} ${Number(installments)===1?"cuota":"cuotas"}<br>Precio por adulto: ${money(activePackage.price)} · Total estimado: ${money(total)}`;const msg=`Hola, soy ${first} ${last}. Quiero continuar con mi reserva en Grupo Vía Rápida.\n\nPaquete: ${activePackage.destination} (${activePackage.id})\nSalida: ${dateLabel(departure)}\n${adultQty} adultos y ${childQty} menores\nPago: ${payment} en ${installments} cuota(s)\nTotal estimado: ${money(total)}\n\nUn asesor se pondrá en contacto para continuar con el proceso y pueda disfrutar del destino que elegí.`;$("#whatsappLink").href=`https://wa.me/?text=${encodeURIComponent(msg)}`;$("#bookingDialog").close();e.currentTarget.reset();$("#successDialog").showModal()});
$("#menuToggle").addEventListener("click",()=>{const n=$(".main-nav"),open=n.classList.toggle("is-open");$("#menuToggle").setAttribute("aria-expanded",String(open))});$(".main-nav").addEventListener("click",e=>{if(e.target.closest("a")){$(".main-nav").classList.remove("is-open");$("#menuToggle").setAttribute("aria-expanded","false")}});
initFilters();renderPackages();


