/* Catálogo editable desde el gestor; se mantiene entre visitas en este navegador. */
const STORE_KEY="viaRapidaPackages";
let packages;
try { packages=JSON.parse(localStorage.getItem(STORE_KEY)) || [...window.viaRapidaInitialPackages]; } catch { packages=[...window.viaRapidaInitialPackages]; }
const money=v=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(v);
const dateLabel=v=>new Intl.DateTimeFormat("es-AR",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`));
const $=s=>document.querySelector(s);const grid=$("#packageGrid"),provinceFilter=$("#provinceFilter"),destinationSearch=$("#destinationSearch"),dateSearch=$("#dateSearch");let cart=[],activePackage=null,adults=1,children=0;
function initFilters(){[...new Set(packages.map(p=>p.province))].sort().forEach(v=>provinceFilter.add(new Option(v,v)));[...new Set(packages.map(p=>p.destination))].sort().forEach(v=>destinationSearch.add(new Option(v,v)));[...new Set(packages.flatMap(p=>p.departures))].sort().forEach(v=>dateSearch.add(new Option(dateLabel(v),v)))}
function refreshFilterOptions(){const province=provinceFilter.value,destination=destinationSearch.value,date=dateSearch.value;provinceFilter.replaceChildren(new Option("Todas las provincias",""));destinationSearch.replaceChildren(new Option("Todos los destinos",""));dateSearch.replaceChildren(new Option("Cualquier fecha",""));initFilters();if([...provinceFilter.options].some(o=>o.value===province))provinceFilter.value=province;if([...destinationSearch.options].some(o=>o.value===destination))destinationSearch.value=destination;if([...dateSearch.options].some(o=>o.value===date))dateSearch.value=date}function renderPackages(){const province=provinceFilter.value,destination=destinationSearch.value,date=dateSearch.value;const list=packages.filter(p=>(!province||p.province===province)&&(!destination||p.destination===destination)&&(!date||p.departures.includes(date)));grid.innerHTML=list.map(p=>`<article class="package-card"><div class="card-photo"><img src="${p.image}" alt="Paisaje de ${p.destination}" loading="lazy"><span class="photo-gradient"></span><span class="category-badge">${p.category}</span><span class="scarcity-badge ${p.featured.toLowerCase().includes("oferta")?"sale":""}">${p.featured}</span><span class="photo-place">${p.province.toUpperCase()} · ARGENTINA</span></div><div class="card-body"><span class="card-duration">${p.nights} noches · ${p.days} días</span><h3>${p.destination}</h3><p class="card-description">${p.description}</p><div class="includes-list">${p.includes.map(i=>`<span class="include-chip">${i}</span>`).join("")}</div><div class="card-divider"></div><div class="card-price-row"><div><span class="price-label">Desde · por persona</span><strong class="card-price">${money(p.price)}</strong></div><span class="price-note">ARS</span></div><div class="card-actions"><button class="button button-outline" data-action="detail" data-id="${p.id}">Ver detalle</button><button class="button button-primary" data-action="book" data-id="${p.id}">Reservar ahora</button></div></div></article>`).join("");$("#resultsCount").textContent=`${list.length} ${list.length===1?"experiencia disponible":"experiencias disponibles"}`;$("#emptyState").hidden=list.length!==0;$("#clearFilters").hidden=!(province||destination||date)}
function byId(id){return packages.find(p=>p.id===id)}
function openDetail(id){const p=byId(id);if(!p)return;$("#detailContent").innerHTML=`<img class="detail-image" src="${p.image}" alt="Paisaje de ${p.destination}"><div class="detail-body"><p class="eyebrow">${p.category.toUpperCase()} · ${p.province.toUpperCase()}</p><h2 id="detailTitle">${p.destination} <em>te espera</em></h2><p>${p.description}</p><div class="detail-facts"><span>◷ ${p.nights} noches / ${p.days} días</span><span>♧ ${p.spots} cupos disponibles</span><span>↗ ${p.departures.length} fechas de salida</span></div><p><strong>Un viaje para disfrutar</strong><br>${p.itinerary}</p><div class="detail-includes"><strong>El paquete incluye:</strong><br>${p.includes.map(i=>`✓ ${i}`).join("<br>")}</div><div class="detail-footer"><strong>${money(p.price)} <small style="font:400 10px var(--body)">por persona</small></strong><button class="button button-primary" data-action="book" data-id="${p.id}">Reservar ahora →</button></div></div>`;$("#detailDialog").showModal()}
function openBooking(id){const p=byId(id);if(!p)return;activePackage=p;adults=1;children=0;$("#bookingSummary").innerHTML=`<img src="${p.image}" alt="${p.destination}"><p class="summary-label">TU PRÓXIMO DESTINO</p><h3>${p.destination}</h3><p>${p.nights} noches · ${p.days} días<br>${p.includes.join(" · ")}</p><strong>${money(p.price)} <small style="font:400 9px var(--body)">/ persona</small></strong>`;$("#bookingForm").reset();$("#bookingPackageId").value=p.id;const dep=$("#bookingDeparture");dep.replaceChildren(...p.departures.map(d=>new Option(dateLabel(d),d)));$("#adultCount").textContent=1;$("#childCount").textContent=0;$("[name=adults]").value=1;$("[name=children]").value=0;$("#bookingDialog").showModal()}
function openCart(){$("#cartContent").innerHTML=cart.length?`<div class="cart-list">${cart.map((x,i)=>`<div class="cart-item"><img src="${x.image}" alt=""><div><strong>${x.destination}</strong><small>${dateLabel(x.departure)} · ${x.travelers} viajeros</small></div><button data-remove="${i}">Quitar</button></div>`).join("")}</div>`:`<p class="cart-empty">Todavía no tenés reservas. Encontrá tu próximo viaje y guardalo acá.</p>`;$("#cartDialog").showModal()}
function updateCart(){$("#cartCount").textContent=cart.length}
document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;if(b.dataset.action==="detail")openDetail(b.dataset.id);if(b.dataset.action==="book"){$("#detailDialog").close();openBooking(b.dataset.id)}});
provinceFilter.addEventListener("change",renderPackages);$("#tripSearch").addEventListener("submit",e=>{e.preventDefault();renderPackages();$("#paquetes").scrollIntoView({behavior:"smooth"})});$("#clearFilters").addEventListener("click",()=>{provinceFilter.value="";destinationSearch.value="";dateSearch.value="";renderPackages()});$("#cartButton").addEventListener("click",openCart);$("#cartContent").addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(b){cart.splice(Number(b.dataset.remove),1);updateCart();openCart()}});
document.addEventListener("click",e=>{const b=e.target.closest("[data-step]");if(b){const key=b.dataset.step,delta=Number(b.dataset.change);if(key==="adults")adults=Math.max(1,Math.min(9,adults+delta));else children=Math.max(0,Math.min(9,children+delta));$(key==="adults"?"#adultCount":"#childCount").textContent=key==="adults"?adults:children;$(`[name=${key}]`).value=key==="adults"?adults:children}if(e.target.matches("[data-close]"))e.target.closest("dialog").close()});
$("#bookingForm").addEventListener("submit",e=>{e.preventDefault();if(!activePackage)return;const f=new FormData(e.currentTarget),departure=f.get("departure"),payment=f.get("payment"),installments=f.get("installments"),adultQty=Number(f.get("adults")),childQty=Number(f.get("children")),total=activePackage.price*adultQty,first=f.get("firstName"),last=f.get("lastName"),dni=f.get("dni"),email=f.get("email"),phone=f.get("phone");cart.push({...activePackage,departure,travelers:adultQty+childQty,adults:adultQty,children:childQty,total});updateCart();
  $("#successSummary").innerHTML=`<strong>${activePackage.destination} (${activePackage.id})</strong><br>Salida: ${dateLabel(departure)} · ${activePackage.nights} noches / ${activePackage.days} días<br>Pasajero: ${first} ${last} · DNI ${dni}<br>Correo: ${email} · Celular: ${phone}<br>Viajeros: ${adultQty} adultos (mayores de 4 años) · ${childQty} menores (menores de 4 años)<br>Pago: ${payment} · ${installments} ${Number(installments)===1?"cuota":"cuotas"}<br>Precio por adulto: ${money(activePackage.price)} · Total estimado (adultos; tarifa de menores a confirmar): ${money(total)}`;
  const msg=`Hola, somos grupoviarapida. Gracias por elegirnos. Quiero continuar con esta reserva.\n\nDATOS DEL VIAJE\nPaquete: ${activePackage.destination} (${activePackage.id})\nProvincia: ${activePackage.province}\nSalida: ${dateLabel(departure)}\nDuración: ${activePackage.nights} noches / ${activePackage.days} días\n\nDATOS DEL PASAJERO\nNombre y apellido: ${first} ${last}\nDNI: ${dni}\nCorreo electrónico: ${email}\nCelular: ${phone}\n\nINTEGRANTES\nAdultos (mayores de 4 años): ${adultQty}\nMenores (menores de 4 años): ${childQty}\n\nMODALIDAD DE PAGO\nMedio: ${payment}\nCuotas: ${installments}\nPrecio por adulto: ${money(activePackage.price)}\nTotal estimado (adultos; tarifa de menores a confirmar): ${money(total)}\n\nUn asesor se pondrá en contacto para continuar con el proceso y puedas disfrutar del destino que elegiste.`;
  $("#whatsappLink").href=`https://wa.me/5493624331163?text=${encodeURIComponent(msg)}`;$("#bookingDialog").close();e.currentTarget.reset();$("#successDialog").showModal()});$("#menuToggle").addEventListener("click",()=>{const n=$(".main-nav"),open=n.classList.toggle("is-open");$("#menuToggle").setAttribute("aria-expanded",String(open))});$(".main-nav").addEventListener("click",e=>{if(e.target.closest("a")){$(".main-nav").classList.remove("is-open");$("#menuToggle").setAttribute("aria-expanded","false")}});
initFilters();renderPackages();






/* Gestor visual sencillo para editar el catálogo desde la misma página. */
const adminDialog=$("#packageManagerDialog"),adminForm=$("#packageAdminForm");
function safeText(value){return String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function drawManagerList(){$("#managerItems").innerHTML=packages.map(p=>`<article class="manager-item"><div><strong>${safeText(p.destination)}</strong><small>${safeText(p.province)} · ${money(p.price)}</small></div><button type="button" data-edit-package="${safeText(p.id)}">Editar</button><button type="button" class="manager-delete" data-delete-package="${safeText(p.id)}">Eliminar</button></article>`).join("")||`<p class="cart-empty">Todavía no hay paquetes. Creá el primero con “Nuevo paquete”.</p>`}
function resetPackageEditor(){adminForm.reset();adminForm.elements.namedItem("id").value="";$("#editorTitle").textContent="Nuevo paquete";$("#managerNotice").textContent=""}
function openPackageEditor(id){resetPackageEditor();if(id){const p=byId(id);if(!p)return;$("#editorTitle").textContent=`Editar ${p.destination}`;for(const key of ["id","destination","province","category","featured","description","itinerary","nights","days","price","spots","image"])adminForm.elements.namedItem(key).value=p[key];adminForm.elements.namedItem("includes").value=p.includes.join(", ");adminForm.elements.namedItem("departures").value=p.departures.join(", ")}adminDialog.showModal()}
$("#openPackageManager").addEventListener("click",e=>{e.preventDefault();drawManagerList();resetPackageEditor();adminDialog.showModal()});$("#newPackage").addEventListener("click",()=>openPackageEditor());$("#cancelEdit").addEventListener("click",resetPackageEditor);
$("#managerItems").addEventListener("click",e=>{const edit=e.target.closest("[data-edit-package]"),remove=e.target.closest("[data-delete-package]");if(edit)openPackageEditor(edit.dataset.editPackage);if(remove){const p=byId(remove.dataset.deletePackage);if(!p||!confirm(`¿Eliminar el paquete ${p.destination}?`))return;packages=packages.filter(item=>item.id!==p.id);try{localStorage.setItem(STORE_KEY,JSON.stringify(packages));drawManagerList();refreshFilterOptions();renderPackages();$("#managerNotice").textContent=`${p.destination} eliminado.`}catch{$("#managerNotice").textContent="El navegador no permitió guardar el cambio."}}});
adminForm.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(adminForm),existingId=f.get("id"),departures=f.get("departures").split(",").map(v=>v.trim()).filter(Boolean),image=f.get("image").trim();if(!departures.length||departures.some(d=>!/^\d{4}-\d{2}-\d{2}$/.test(d))){$("#managerNotice").textContent="Ingresá al menos una fecha con formato AAAA-MM-DD.";return}if(!/^(https?:\/\/|assets\/)/i.test(image)){$("#managerNotice").textContent="La imagen debe ser una URL segura o estar dentro de assets/.";return}const item={id:existingId||`ARG-${Date.now().toString().slice(-6)}`,destination:f.get("destination").trim(),province:f.get("province").trim(),category:f.get("category").trim(),description:f.get("description").trim(),itinerary:f.get("itinerary").trim(),nights:Number(f.get("nights")),days:Number(f.get("days")),includes:f.get("includes").split(",").map(v=>v.trim()).filter(Boolean),price:Number(f.get("price")),spots:Number(f.get("spots")),departures,image,featured:f.get("featured").trim()};const index=packages.findIndex(p=>p.id===existingId);if(index>=0)packages[index]=item;else packages.push(item);try{localStorage.setItem(STORE_KEY,JSON.stringify(packages));drawManagerList();refreshFilterOptions();renderPackages();resetPackageEditor();$("#managerNotice").textContent=`${item.destination} guardado correctamente.`}catch{$("#managerNotice").textContent="No se pudo guardar. Revisá el espacio disponible del navegador."}});
drawManagerList();




